name: Celebrate Contributors

on:
  schedule:
    - cron: '* * * * *'  # Runs every day at 00:00 UTC
  workflow_call:

jobs:
  celebrate-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find Contributors
        id: contributors
        run: |
          response=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/contributors")
      
      - name: Set Output
        run: echo response="$response" >> $GITHUB_OUTPUT

      - name: Generate Contributors Table and Graph
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Contributions Table
        run: python contributors_table.py $GITHUB_OUTPUT

      - name: Generate Contributions Graph
        run: python contributors_graph.py $GITHUB_OUTPUT
