name: Celebrate Contributors

on:
  schedule:
    - cron: '* * * * *'  # testing
    # - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_call:

jobs:
  celebrate-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find Contributions then Generate Table and Graph
        run: python celebrate_contributors.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add CONTRIBUTORS.md
          git commit -m "Update contributors file"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push