name: Celebrate Contributors

on:
  schedule:
    - cron: '* * * * *'  # testing
    # - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_call:

jobs:
  celebrate-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find Contributions then Generate Table and Graph
        run: python celebrate_contributors.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}
